### ISSUE TITLE
Warning deprecated recipe.preproc.macros

### ISSUE THREAD

**Issue by tschertel** [jensh/attiny13a#1]
When compiling any sketch, compiler warns about a deprecated macro call (line 86).
But it also says that it is automatically converted to the right macro.
The only difference is the " **-o "{preprocessed_file_path}"**" added at end of line.

**Comment by tschertel** [comment]
By the way, thanks for your work. ;)

**Comment by jensh** [comment]
Thank you for your report!
Could you please attach the full compiler output and arduino version/ gcc version you are using? I can not reproduce the warning with arduino 1.6.6 (avr-gcc 4.8.1) on linux (fedora 23). Which macro is deprecated and in which file it is used?

**Comment by tschertel** [comment]
Hi Jens.

My system (Arch Linux) has avr-gcc (GCC) 5.3.0 installed.
I'm using Arduino 1.6.9, witch uses avr-gcc (GCC) 4.8.1.

Sorry. File is attiny13a/avr/platform.txt, line 86.
To solve that, I just added  **_-o "{preprocessed_file_path}"_** to the end of this line.

`/usr/share/arduino/arduino-builder -dump-prefs -logger=machine -hardware "/usr/share/arduino/hardware" -hardware "/home/tomas/.arduino15/packages" -hardware "/home/tomas/Arduino/hardware" -tools "/usr/share/arduino/tools-builder" -tools "/usr/share/arduino/hardware/tools/avr" -tools "/home/tomas/.arduino15/packages" -built-in-libraries "/usr/share/arduino/libraries" -libraries "/home/tomas/Arduino/libraries" -fqbn=attiny13a:avr:attiny13:CpuFrequency=9_6M -ide-version=10609 -build-path "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "/tmp/untitled1557162391.tmp/sketch_jul04a/sketch_jul04a.ino"
/usr/share/arduino/arduino-builder -compile -logger=machine -hardware "/usr/share/arduino/hardware" -hardware "/home/tomas/.arduino15/packages" -hardware "/home/tomas/Arduino/hardware" -tools "/usr/share/arduino/tools-builder" -tools "/usr/share/arduino/hardware/tools/avr" -tools "/home/tomas/.arduino15/packages" -built-in-libraries "/usr/share/arduino/libraries" -libraries "/home/tomas/Arduino/libraries" -fqbn=attiny13a:avr:attiny13:CpuFrequency=9_6M -ide-version=10609 -build-path "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp" -warnings=all -prefs=build.warn_data_percentage=75 -verbose "/tmp/untitled1557162391.tmp/sketch_jul04a/sketch_jul04a.ino"
Warning: platform.txt from core 'ATtiny13A' contains deprecated recipe.preproc.macros="{compiler.path}{compiler.cpp.cmd}" {compiler.cpp.flags} {preproc.macros.flags} -mmcu={build.mcu} -DF_CPU={build.f_cpu} -DARDUINO={runtime.ide.version} -DARDUINO_{build.board} -DARDUINO_ARCH_{build.arch} {compiler.cpp.extra_flags} {build.extra_flags} {includes} "{source_file}", automatically converted to recipe.preproc.macros="{compiler.path}{compiler.cpp.cmd}" {compiler.cpp.flags} {preproc.macros.flags} -mmcu={build.mcu} -DF_CPU={build.f_cpu} -DARDUINO={runtime.ide.version} -DARDUINO_{build.board} -DARDUINO_ARCH_{build.arch} {compiler.cpp.extra_flags} {build.extra_flags} {includes} "{source_file}" -o "{preprocessed_file_path}". Consider upgrading this core.
"/usr/share/arduino/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=attiny13a -DF_CPU=9600000L -DARDUINO=10609 -DARDUINO_attiny13a -DARDUINO_ARCH_AVR   "-I/home/tomas/Arduino/hardware/attiny13a/avr/cores/core13" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch/sketch_jul04a.ino.cpp" -o "/dev/null"
"/usr/share/arduino/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=attiny13a -DF_CPU=9600000L -DARDUINO=10609 -DARDUINO_attiny13a -DARDUINO_ARCH_AVR   "-I/home/tomas/Arduino/hardware/attiny13a/avr/cores/core13" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch/sketch_jul04a.ino.cpp" -o "/dev/null"
"/usr/share/arduino/hardware/tools/avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=attiny13a -DF_CPU=9600000L -DARDUINO=10609 -DARDUINO_attiny13a -DARDUINO_ARCH_AVR   "-I/home/tomas/Arduino/hardware/attiny13a/avr/cores/core13" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch/sketch_jul04a.ino.cpp" -o "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
"/usr/share/arduino/tools-builder/ctags/5.8-arduino10/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/preproc/ctags_target_for_gcc_minus_e.cpp"
"/usr/share/arduino/hardware/tools/avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=attiny13a -DF_CPU=9600000L -DARDUINO=10609 -DARDUINO_attiny13a -DARDUINO_ARCH_AVR   "-I/home/tomas/Arduino/hardware/attiny13a/avr/cores/core13" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch/sketch_jul04a.ino.cpp" -o "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch/sketch_jul04a.ino.cpp.o"
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/pins_arduino.c.o
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/wiring.c.o
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/wiring_analog.c.o
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/wiring_digital.c.o
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/wiring_shift.c.o
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/Print.cpp.o
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/WMath.cpp.o
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/events.cpp.o
Using previously compiled file: /tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/main.cpp.o
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/pins_arduino.c.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/wiring.c.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/wiring_analog.c.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/wiring_digital.c.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/wiring_shift.c.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/Print.cpp.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/WMath.cpp.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/events.cpp.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-ar" rcs  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/main.cpp.o"
"/usr/share/arduino/hardware/tools/avr/bin/avr-gcc" -Wall -Wextra -Os -Wl,--gc-sections -mmcu=attiny13a  -o "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch_jul04a.ino.elf" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch/sketch_jul04a.ino.cpp.o" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/core/core.a" "-L/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp" -lm
"/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy" -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch_jul04a.ino.elf" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch_jul04a.ino.eep"
"/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy" -O ihex -R .eeprom  "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch_jul04a.ino.elf" "/tmp/builda28d82e64b33065cb08fe8e7cb9c45a0.tmp/sketch_jul04a.ino.hex"

Sketch uses 172 bytes (16%) of program storage space. Maximum is 1,024 bytes.
Global variables use 4 bytes of dynamic memory.`

**Comment by jensh** [comment]
Thanks again. Unfortunately the fix is incompatible with 1.6.6. But well...

**Comment by tschertel** [comment]
Thanks for your time.
Any thing to help you.

Is it possible to add attiny2313 support? I'll open a request for that, is it OK?

**Comment by jensh** [comment]
A request is ok, but probably i will not work on it until i get a project using the 2313. I did not looked inside the 2313 specs in deep, but maybe the attiny45/85 has more in common with the 2313 or even with the mega328 than the attiny13? Do you know https://github.com/damellis/attiny ?

**Comment by tschertel** [comment]
Yes, I know damellis work and I use it already. It's great.
As far as I know, 2313 and 13 differs just on number of pins.

Anyway, thanks for your effort.
